# ZShaolin shell configuration

# Distributed configuration
# put your tweaks in ~/.profile instead of here

# setup zsh modules path
fpath=(
    $SYS/share/zsh/5.0.2/functions
    $SYS/share/zsh/site-functions
)

# GRML configuration - grml.org/zsh
source $SYS/etc/grmlrc
{ test -r ~/.grml.conf } && { source ~/.grml.conf }

# Vim configuration
export VIMRUNTIME=${SYS}/share/vim/vim73

# Midnight commander
alias mc='mc -aX' # correct rendering

# Lynx web browser
alias lynx="lynx -cfg ${SYS}/etc/lynx.cfg -lss ${SYS}/etc/lynx.lss"

# Custom user configuration
{ test -r ~/.profile } && { source ~/.profile }

return 0
